server:
  port: 0

echo:
  message:
    text: 'Hello, World! Santhosh !!'

spring:
  application:
    name: spring-cloud-bus-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:29092
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
endpoints:
  spring:
    cloud:
      bus:
        refresh:
          enabled: true
        env:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: busrefresh
        
