adhoc:
  value: ${spring.application.instance_id:${random.value}}

eureka:
  instance:
    instance-id: ${spring.application.name}:${adhoc.value}

echo:
  message:
    text: 'Hello World.. Janaki !!'

spring:
  application:
    name: spring-cloud-bus-service
  cloud:
    enabled: true
    uri: http://localhost:8888
    stream:
      bindings:
        springCloudBusInput:
          group: CG.${spring.application.name}.${adhoc.value}
          destination: TP.POC.CONFIG.REFRESH
        springCloudBusOutput:
          destination: TP.POC.CONFIG.REFRESH
  bus:
    enabled: true
    destination: TP.POC.CONFIG.REFRESH
    id: ${spring.application.name}:${adhoc.value}
    trace:
      enabled: true
    refresh:
      enabled: true
    env:
      enabled: true
  kafka:
    bootstrap-servers: localhost:29092

management:
  endpoints:
    web:
      exposure:
        include: busrefresh,health,info,env,metrics
  endpoint:
    env:
      show-values: ALWAYS
