server:
  port: 0

echo:
  message:
    text: 'Hello, World!'

spring:
  application:
    name: spring-cloud-bus-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:29092
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
        
